# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(default='SOME STRING', upload_to='images'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_url',
            field=models.URLField(default='https://www.nespresso.com/shared_res/nc2/free_html/int/b2b-capsule-plp/img/C-0124-quickViewMediaFormat.png'),
        ),
    ]
