# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20171020_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_image',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
