# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_auto_20171023_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_url',
            field=models.URLField(blank=True, default='https://www.nespresso.com/pro/fr/fr/product/ristretto-intenso-boite-capsule-cafe'),
        ),
    ]
