# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_auto_20171023_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_url',
        ),
    ]
