# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-23 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='question',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
