# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-25 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_auto_20171025_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
