# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0012_order_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
