# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-31 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('coffee', '0013_auto_20171026_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'success'), (2, 'info'), (3, 'warning'), (4, 'danger')], default=2, verbose_name='severity')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('target_groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='target_groups')),
            ],
            options={
                'ordering': ['-end', '-start'],
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
